import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='container relative mx-auto max-w-2xl scroll-my-12 overflow-auto p-4 md:p-16 print:p-12'>
          {children}
        </main>
      </body>
    </html>
  );
}
